=== Techatonic/part-ii-project/src/input_handling/input_schema_constraint_checker.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/main",
    "definitions": {
        "main": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SportElement"
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Event"
                    }
                },
                "general_constraints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ConstraintEnum"
                    }
                },
                "tournament_length": {
                    "type": "integer"
                }
            },
            "required": [
                "events",
                "general_constraints",
                "sports",
                "tournament_length"
            ],
            "title": "Welcome2"
        },
        "Event": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "round": {
                    "$ref": "#/definitions/Round"
                },
                "sport": {
                    "$ref": "#/definitions/SportEnum"
                },
                "event_id": {
                    "type": "integer"
                },
                "venue": {
                    "type": "string"
                },
                "day": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "duration": {
                    "type": "number"
                },
                "teams_involved": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "day",
                "duration",
                "event_id",
                "round",
                "sport",
                "start_time",
                "teams_involved",
                "venue"
            ],
            "title": "Event"
        },
        "SportElement": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "$ref": "#/definitions/SportEnum"
                },
                "venues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Venue"
                    }
                },
                "teams": {
                    "type": "array",
                    "title": "The teams Schema",
                    "items": {
                        "type": "string",
                        "title": "Team name",
                        "examples": ["Great Britain", "Novak Djokovic"]
                    }
                },
                "num_teams_per_game": {
                    "type": "integer"
                },
                "is_knockout": {
                    "type": "boolean"
                },
                "group_stage": {
                    "type": "null"
                },
                "min_start_day": {
                    "type": "integer"
                },
                "max_finish_day": {
                    "type": "integer"
                },
                "min_start_time": {
                    "type": "integer"
                },
                "max_finish_time": {
                    "type": "integer"
                },
                "duration": {
                    "type": "number"
                },
                "constraints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ConstraintEnum"
                    }
                }
            },
            "required": [
                "constraints",
                "duration",
                "group_stage",
                "is_knockout",
                "max_finish_day",
                "max_finish_time",
                "min_start_day",
                "min_start_time",
                "name",
                "teams",
                "num_teams_per_game",
                "venues"
            ],
            "title": "SportElement"
        },
        "Venue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "location_coordinates": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "location_address": {
                    "$ref": "#/definitions/LocationAddress"
                },
                "location_postcode": {
                    "$ref": "#/definitions/LocationPostcode"
                },
                "min_start_time": {
                    "type": "integer"
                },
                "max_finish_time": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "max_matches_per_day": {
                    "type": "integer"
                }
            },
            "required": [
                "capacity",
                "location_address",
                "location_coordinates",
                "location_postcode",
                "max_finish_time",
                "max_matches_per_day",
                "min_start_time",
                "name"
            ],
            "title": "Venue"
        },
        "Round": {
            "type": "string",
            "enum": [
                "Final",
                "Semi Final",
                "Quarter Final",
                "Round of 16",
                "Round of 32",
                "Round of 64",
                "Round of 128"
            ],
            "title": "Round"
        },
        "SportEnum": {
            "type": "string",
            "enum": [
                "boxing_heavyweight",
                "football",
                "tennis"
            ],
            "title": "SportEnum"
        },
        "LocationAddress": {
            "type": "string",
            "enum": [
                "Fulham Rd., London SW6 1HS"
            ],
            "title": "LocationAddress"
        },
        "LocationPostcode": {
            "type": "string",
            "enum": [
                "SW6 1HS"
            ],
            "title": "LocationPostcode"
        },
        "ConstraintEnum": {
            "type": "string",
            "enum": [
                "same_venue_overlapping_time_constraint_check",
                "no_later_rounds_before_earlier_rounds_constraint_check",
                "same_venue_max_matches_per_day",
                "team_time_between_matches",
                "venue_time_between_matches"
            ]
        }
    }
}

=== Techatonic/part-ii-project/examples/inputs/example_input_constraint_checker.json
{
  "sports": [
    {
      "name": "football",
      "venues": [
        {
          "name": "Stamford Bridge",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 40000,
          "max_matches_per_day": 2
        },
        {
          "name": "Olympic Stadium",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 11,
          "max_finish_time": 22,
          "capacity": 40000,
          "max_matches_per_day": 2
        },
        {
          "name": "Emirates Stadium",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 14,
          "max_finish_time": 21,
          "capacity": 40000,
          "max_matches_per_day": 2
        },
        {
          "name": "Tottenham Hotspur Stadium",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 40000,
          "max_matches_per_day": 2
        },
        {
          "name": "The Hive",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 40000,
          "max_matches_per_day": 2
        },
        {
          "name": "Etihad Stadium",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 40000,
          "max_matches_per_day": 2
        }
      ],
      "teams": [
        "Brazil", "Argentina", "France", "Belgium", "England", "Netherlands", "Croatia",
        "Italy", "Portugal", "Spain", "Morocco", "Switzerland", "USA", "Germany", "Mexico", "Uruguay",
        "Colombia", "Denmark", "Senegal", "Japan", "Peru", "Poland", "Sweden",
        "Iran", "South Korea", "Ukraine", "Australia", "Wales", "Serbia", "Tunisia", "Chile", "Costa Rica"
      ],
      "num_teams_per_game": 2,
      "is_knockout": true,
      "group_stage": null,
      "min_start_day": 1,
      "max_finish_day": 10,
      "min_start_time": 12,
      "max_finish_time": 22,
      "duration": 1.5,
      "constraints": [
        "same_venue_overlapping_time_constraint_check",
        "no_later_rounds_before_earlier_rounds_constraint_check",
        "same_venue_max_matches_per_day",
        "team_time_between_matches",
        "venue_time_between_matches"
      ]
    },
    {
      "name": "tennis",
      "venues": [
        {
          "name": "Wimbledon_Centre_Court",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 20000,
          "max_matches_per_day": 1
        },
        {
          "name": "Wimbledon_Court_1",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 20000,
          "max_matches_per_day": 1
        },
        {
          "name": "Wimbledon_Court_2",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 10000,
          "max_matches_per_day": 1
        },
        {
          "name": "Wimbledon_Court_3",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 22,
          "capacity": 5000,
          "max_matches_per_day": 1
        }
      ],
      "teams": [
        "Carlos Alcaraz", "Rafael Nadal", "Casper Ruud", "Stefanos Tsitsipas",
        "Novak Djokovic", "Felix Auger-Aliassime", "Daniil Medvedev", "Andrey Rublev"
      ],
      "num_teams_per_game": 2,
      "is_knockout": true,
      "group_stage": null,
      "min_start_day": 1,
      "max_finish_day": 14,
      "min_start_time": 12,
      "max_finish_time": 23,
      "duration": 3,
      "constraints": [
        "same_venue_overlapping_time_constraint_check",
        "no_later_rounds_before_earlier_rounds_constraint_check",
        "same_venue_max_matches_per_day",
        "team_time_between_matches",
        "venue_time_between_matches"
      ]
    },
    {
      "name": "boxing_heavyweight",
      "venues": [
        {
          "name": "Excel_1",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 20,
          "capacity": 20000,
          "max_matches_per_day": 5
        },
        {
          "name": "Excel_2",
          "location_coordinates": [51.4817, -0.1910],
          "location_address": "Fulham Rd., London SW6 1HS",
          "location_postcode": "SW6 1HS",
          "min_start_time": 12,
          "max_finish_time": 20,
          "capacity": 20000,
          "max_matches_per_day": 5
        }
      ],
      "teams": [
        "Oleksandr Usyk", "Tyson Fury", "Deontay Wilder", "Anthony Joshua", "Joe Joyce", "Andy Ruiz Jr", "Dillian Whyte", "Luis Ortiz"
      ],
      "num_teams_per_game": 2,
      "is_knockout": true,
      "group_stage": null,
      "min_start_day": 1,
      "max_finish_day": 14,
      "min_start_time": 14,
      "max_finish_time": 18,
      "duration": 1,
      "constraints": [
        "same_venue_overlapping_time_constraint_check",
        "no_later_rounds_before_earlier_rounds_constraint_check",
        "same_venue_max_matches_per_day",
        "team_time_between_matches",
        "venue_time_between_matches"
      ]
    }
  ],
  "events": [
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 14,
            "venue": "Emirates Stadium",
            "day": 1,
            "start_time": 16,
            "duration": 1.5,
            "teams_involved": [
                "Australia",
                "Wales"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 7,
            "venue": "Tottenham Hotspur Stadium",
            "day": 1,
            "start_time": 19,
            "duration": 1.5,
            "teams_involved": [
                "USA",
                "Germany"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 6,
            "venue": "Etihad Stadium",
            "day": 2,
            "start_time": 19,
            "duration": 1.5,
            "teams_involved": [
                "Morocco",
                "Switzerland"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 13,
            "venue": "Stamford Bridge",
            "day": 1,
            "start_time": 16,
            "duration": 1.5,
            "teams_involved": [
                "South Korea",
                "Ukraine"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 3,
            "venue": "Emirates Stadium",
            "day": 2,
            "start_time": 17,
            "duration": 1.5,
            "teams_involved": [
                "England",
                "Netherlands"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 12,
            "venue": "Stamford Bridge",
            "day": 2,
            "start_time": 18,
            "duration": 1.5,
            "teams_involved": [
                "Sweden",
                "Iran"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 2,
            "venue": "Stamford Bridge",
            "day": 2,
            "start_time": 14,
            "duration": 1.5,
            "teams_involved": [
                "France",
                "Belgium"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 11,
            "venue": "The Hive",
            "day": 2,
            "start_time": 15,
            "duration": 1.5,
            "teams_involved": [
                "Peru",
                "Poland"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 5,
            "venue": "Etihad Stadium",
            "day": 1,
            "start_time": 15,
            "duration": 1.5,
            "teams_involved": [
                "Portugal",
                "Spain"
            ]
        },
        {
            "round": "Round of 32",
            "sport": "football",
            "event_id": 4,
            "venue": "Olympic Stadium",
            "day": 2,
            "start_time": 19,
            "duration": 1.5,
            "teams_involved": [
                "Croatia",
                "Italy"
            ]
        },
        {
            "round": "Round of 32",
